spring:
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
  datasource:
    url: jdbc:h2:tcp://localhost:1521/~/zerodowntime
    username: sa
    driver-class-name: org.h2.Driver
info:
  app:
    version: @project.version@